spring:
  application:
    name: eureka-server
server:
  port: 2998
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:2998/eureka