server:
  port: 3002
spring:
  application:
    name: manager-service
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2998/eureka/